// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFrames(arg1:Array<any>,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ExtractFrames(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetSystemTheme():Promise<string>;

export function GetTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectGifFile():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
