// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFrames(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportFrames'](arg1, arg2, arg3);
}

export function ExtractFrames(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractFrames'](arg1, arg2, arg3);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectGifFile() {
  return window['go']['main']['App']['SelectGifFile']();
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
